apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-airport-paas
  labels:
    app: argo-airport-paas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-airport-paas
  template:
    metadata:
      labels:
        app: argo-airport-paas
    spec:
      containers:
        - name: argo-airport-paas
          image: ghcr.io/3kmfi6hp/argo-airport-paas:main
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: config-env
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-upstream
  name: ingress-upstream
spec:
  ports:
    - name: 3000-80-tcp
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: argo-airport-paas
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
